---
version: '2'
configuration:
  type: object
  fields:
    value:
      type: number_decimal
      name: Percentage off
      validations:
      - name: min
        value: "0"
      - name: max
        value: "100"
    excludedVariantIds:
      type: array
      name: Excluded Product Variants
      elementType:
        type: variant_reference
        name: Product Variant
