name = "Product Discount"
type = "product_discounts"
api_version = "2022-07"

[ui.paths]
create = "/product-discount/new"
details = "/product-discount/:id"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/product-discount.wasm"
