import path from 'path';
import { readFileIfExists, checkFileExists } from '../utils/file-utils.js';

export async function analyzeGraphQL(functionDir, analysis) {
  const schemaPath = path.join(functionDir, 'schema.graphql');
  const runGraphqlPath = path.join(functionDir, 'src', 'run.graphql.liquid');

  // Check for schema.graphql
  const schemaContent = await readFileIfExists(schemaPath);
  if (!schemaContent) {
    analysis.inconsistencies.push({
      file: schemaPath,
      issue: 'Missing required schema.graphql file'
    });
  } else {
    // Check for auto-generated comments
    const autoGeneratedComment = schemaContent.includes('# This file is auto-generated') || 
                               schemaContent.includes('# please edit the ruby definition files') ||
                               schemaContent.includes('# Check out the "Docs" tab');

    if (autoGeneratedComment) {
      analysis.inconsistencies.push({
        file: schemaPath,
        issue: 'Contains auto-generated comments that should be removed',
        fix: 'Remove the auto-generated comment block from the top of the file'
      });
    }
  }

  // Check for run.graphql.liquid
  const hasRunGraphql = await checkFileExists(runGraphqlPath);
  if (!hasRunGraphql) {
    analysis.inconsistencies.push({
      file: runGraphqlPath,
      issue: 'Missing required run.graphql.liquid file'
    });
  }

  // Check for any additional .graphql.liquid files referenced in shopify.extension.toml
  const extensionTomlPath = path.join(functionDir, 'shopify.extension.toml.liquid');
  const extensionContent = await readFileIfExists(extensionTomlPath);
  if (extensionContent) {
    const inputQueryMatches = extensionContent.match(/input_query\s*=\s*"([^"]+)"/g) || [];
    
    for (const match of inputQueryMatches) {
      const queryPath = match.split('"')[1];
      const fullPath = path.join(functionDir, queryPath);
      
      const hasQueryFile = await checkFileExists(fullPath);
      if (!hasQueryFile) {
        analysis.inconsistencies.push({
          file: fullPath,
          issue: `Missing GraphQL query file referenced in shopify.extension.toml.liquid`
        });
      }
    }
  }
} 