api_version = "unstable"

[[extensions]]
handle = "{{handle}}"
name = "{{name}}"
type = "function"

  [[extensions.targeting]]
  target = "purchase.pickup-point-delivery-option-generator.fetch"
  input_query = "src/fetch.graphql"
  export = "fetch"

  [[extensions.targeting]]
  target = "purchase.pickup-point-delivery-option-generator.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
