name = "{{name}}"
type = "{{extensionType}}"
api_version = "2022-07"

[build]
command = "/usr/local/wasi-sdk-16.0/bin/clang++ -Oz -fno-exceptions -std=c++17 src/main.cpp -o build/main.wasm"
path = "build/main.wasm"

[ui.paths]
create = ""
details = ""

