---
version: '2'
title: Percentage
description: Percentage discount
configuration:
  type: object
  fields:
    value:
      type: number_integer
      name: Value
      validations:
      - name: min
        value: "0"
      - name: max
        value: "100"
