---
version: '2'
title: Filter shipping method on threshold
description: Hide shipping methods based on the order amount
configuration:
  type: object
  fields:
    shippingMethodName:
      name: Shipping method to hide
      type: single_line_text_field
    threshold:
      name: Order amount
      type: number_decimal
      helpText: Checkout totals greater than this threshold (in CAD) will hide the specified
        shipping method.
