[package]
name = "default"
version = "1.0.0"
edition = "2021"

[dependencies]
rmp-serde = "0.15.5"
serde = { version = "1.0.13", features = ["derive"] }
serde_json = "1.0"

[profile.release]
lto = true
opt-level = 's'
