---
version: '2'
title: Sort payment methods
description: Sort payment methods alphabetically at checkout
configuration:
  type: object
  fields:
    sortDirection:
      name: Sort order
      helpText: Enter ASCENDING or DESCENDING.
      type: single_line_text_field
