---
version: '2'
title: prototype
description: prototype script
configuration:
  type: object
  fields:
    percentage:
      type: number_decimal
      name: Percentage off
      validations:
      - name: min
        value: "0"
      - name: max
        value: "100"
    minimum_order_subtotal:
      type: money
      name: Minimum order subtotal
