---
version: '2'
title: Filter payment method on threshold
description: Hide payment methods based on the order amount
configuration:
  type: object
  fields:
    paymentMethodName:
      name: Payment methods to hide
      type: single_line_text_field
    threshold:
      name: Order amount
      type: number_decimal
      helpText: Checkout totals greater than this threshold (in CAD) will hide the specified
        payment method.
